version: '3'

services:
  db:
    image: redis:5.0.3

  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=db
      - APP_DEBUG=True
    depends_on:
      - db
